version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: challenge_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: challenge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
